// src/lib/components/Footer/Footer.svelte
<script lang="ts">
	const socials = [
		{ label: 'duinlaurens2@gmail.com', href: 'mailto:duinlaurens2@gmail.com' },
		{ label: 'LinkedIn', href: 'https://www.linkedin.com/in/laurens-duin-497b9a1a9/' },
		{ label: 'Github', href: 'https://github.com/Laurens256/' },
	];
</script>

<footer class="root">
	<section>
		<h2 id="__footer_socials__" class="heading">Contact</h2>
		<ul aria-labelledby="__footer_socials__" class="socialsList">
			{#each socials as { label, href }}
				<li>
					<a
						{href}
						target="_blank"
						class="underline socialLink"
					>
						{label}
					</a>
				</li>
			{/each}
		</ul>
	</section>

	<p class="copyrightText">&copy; {new Date().getFullYear()} Laurens Duin</p>
</footer>

<style>
	.root {
		width: 100%;
		background-color: var(--secondary-bg);
		padding-inline: calc((100% - var(--page-width)) / 2);
		padding-block: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.heading {
		font-size: 1.1rem;
	}
	.socialsList {
		display: flex;
		column-gap: 1.5rem;
		row-gap: 0.5rem;
		margin-top: 0.25rem;
		flex-wrap: wrap;

		@media screen and (max-width: 500px) {
			flex-direction: column;
		}
	}
	.socialLink {
		color: var(--primary-text);
		font-family: var(--font-sans-serif);
	}

	.copyrightText {
		font-size: 0.8rem;
		color: var(--secondary-text);
	}
</style>

// src/components/footer/Footer.tsx
import styles from './footer.module.css';
import ThemeSwitcher from '@/parts/themeSwitcher/ThemeSwitcher';

const socials = [
	{ name: 'Github', link: 'https://github.com/Laurens256/' },
	{ name: 'LinkedIn', link: 'https://www.linkedin.com/in/laurens-duin-497b9a1a9/' },
	{ name: 'duinlaurens2@gmail.com', link: 'mailto:duinlaurens2@gmail.com' }
];

export default function Footer({ route }: { route: string }) {
	return (
		<footer className={`${styles.footer} ${styles[route]}`}>
				<section>
					<h3 id="socials">Socials</h3>
					<ul>
						{socials.map((social) => (
							<li key={social.name}>
								<a href={social.link} className="underline" target="_blank">
									{social.name}
								</a>
							</li>
						))}
						<li className={styles['theme-switcher-container']}>
							<ThemeSwitcher />
						</li>
					</ul>
				</section>
		</footer>
	);
}
